apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-argocd-apps
  namespace: argocd
spec:
  project: default
  source:
    path: "argo-infra-apps/"
    repoURL: https://github.com/markopolo123/home-cluster.git
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
