# https://taskfile.dev

version: "3"

tasks:
  init-argocd:
    cmds:
      - kubectl create namespace argocd
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - kubectl apply -f argo-cd-cm.yaml
    silent: true
  bootstrap-cluster:
    cmds:
      - kubectl apply -f clusterservices.yaml
      - kubectl apply -f infra-apps.yaml
      - kubectl apply -f apps.yaml
    silent: true
