provider:
  name: pihole
extraArgs:
  - --source=gateway-httproute
  - --label-filter=external-dns==yes
  - --registry=noop
  - --policy=upsert-only
  - --provider=pihole
env:
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: EXTERNAL_DNS_PIHOLE_SERVER
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: EXTERNAL_DNS_PIHOLE_PASSWORD
