---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas-nfs
  resources:
    requests:
      storage: 100Mi
