---
# helm install connect 1password/connect --set-file connect.credentials=<path/to/1password-credentials.json>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: op
  namespace: argocd
spec:
  project: default
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.15.0
    helm:
      releaseName: connect
      values: |
        operator:
          create: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: op
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
