# https://taskfile.dev

version: "3"

tasks:
  init:
    cmds:
      - op inject -f -i templates/bootstrap.tpl -o bootstrap.yaml
      - kubectl apply -f bootstrap.yaml
      - kubectl apply -f op.yaml
    silent: true
