# https://taskfile.dev

version: "3"

tasks:
  install-crds:
    cmds:
      - kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml
    silent: true
