---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wakapi
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/markopolo123/wakapi-helm-chart.git
    path: src/wakapi
    targetRevision: HEAD
    helm:
      releaseName: wakapi
      values: |
        exposeMetrics: true
        persistence:
          enabled: true
          existingClaim: wakapi-pvc
  destination:
    server: "https://kubernetes.default.svc"
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: wakapi-route
  namespace: apps
  labels:
    gateway: my-gateway
    external-dns: "yes"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: https-listener
  hostnames:
    - "wakapi.internal.sharpley.xyz"
  rules:
    - backendRefs:
        - name: wakapi
          port: 80
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: wakapi
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  itemPath: "vaults/homelab/items/iq24thct4zmwvzeqrmmdpij22u"
