apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      releaseName: nfs
      values: |
        nfs:
          server: nas.internal.sharpley.xyz
          path: /volume1/k8s-nfs
          storageClass: 
            name: nas-nfs
            reclaimPolicy: Retain
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
