---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"

spec:
  project: default
  source:
    chart: cilium
    targetRevision: 1.15.0
    repoURL: https://helm.cilium.io/
    helm:
      releaseName: cilium
      values: |
        operator:
          replicas: 1

        kubeProxyReplacement: true

        l2announcements:
          enabled: true

        k8sClientRateLimit:
          qps: 32
          burst: 60

        kubeProxyReplacementMode: strict

        k8sServiceHost: "192.168.0.142"
        k8sServicePort: 6443

        gatewayAPI:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
