---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  project: default
  source:
    chart: cilium
    targetRevision: 1.15.0
    repoURL: https://helm.cilium.io/
    helm:
      releaseName: cilium
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
