# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  install-crds:
    cmds:
      - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/experimental-install.yaml
    silent: true
