operator:
  replicas: 1

kubeProxyReplacement: true

l2announcements:
  enabled: true

k8sClientRateLimit:
  qps: 32
  burst: 60

kubeProxyReplacementMode: strict

k8sServiceHost: "192.168.0.142"
k8sServicePort: 6443

gatewayAPI:
  enabled: true
